#!/usr/bin/env python3

"""
Copyright 2025 Christian Seberino

This file is part of Pylayers.

Pylayers is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

Pylayers is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
Pylayers. If not, see <https://www.gnu.org/licenses/>.

________________________________________________________________________________


Contains a script that converts source code to intermediate code

Relies on the tokenizer, parser and intermediate code generator.
"""

import tokenizer
import parser
import int_code_gen
import sys

if len(sys.argv) != 2:
        print("Usage: ./int_code <source code file>")
        sys.exit(0)

with open(sys.argv[1]) as f:
        tokens   = tokenizer.tokenizer(f.read())
        ast      = parser.parser(tokens)
        int_code = int_code_gen.int_code_gen(ast)
        print(int_code)
