#!/usr/bin/env python3

"""
Copyright 2025 Christian Seberino

This file is part of Pylayers.

Pylayers is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

Pylayers is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
Pylayers. If not, see <https://www.gnu.org/licenses/>.

________________________________________________________________________________


Contains a script that converts intermediate code to assembly code.

asdfasdf
"""

import asm_code_gen
import sys

if len(sys.argv) != 2:
        print("Usage: ./int_to_asm <intermediate code file>")
        sys.exit(0)

with open(sys.argv[1]) as f:
        int_code      = f.read()
        assembly_code = asm_code_gen.asm_code_gen(int_code)
        print(assembly_code)
