#!/usr/bin/env python3

"""
Copyright 2025 Christian Seberino

This file is part of Pylayers.

Pylayers is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

Pylayers is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
Pylayers. If not, see <https://www.gnu.org/licenses/>.

________________________________________________________________________________


Contains the interpreter.

Executes intermediate code in files.  The intermediate code is in a language
that is a minimal variant of the Lisp language.  Programs contain expressions
which are atoms or lists.  Atoms are booleans, integers, strings, variables,
functions and macros.  Lists can contain other lists.  Running programs is
evaluating expressions.  Evaluating atoms, except for variables, returns them.
Evaluating variables involves environments.  Evaluating lists involves function
or macro invocations.  All functions in the language are implemented in the
language except for the following:

        quote
        if
        set
        func
        macro
        equal
        atom
        first
        rest
        append
        add
        negate
        gt
        print

The first five have special evaluation procedures.  The last one prints
evaluation results.
"""

import eval_
import exps
import sys
import os

LIBRARY   = os.path.dirname(os.path.realpath(__file__)) + "/library"

if len(sys.argv) != 2:
        print("Usage: ./interpreter <intermediate code file>")
        sys.exit(0)

def make_env():
        """
        Creates the environment.

        Installs the library.
        """

        env = [e for e in dir(eval_) if e.startswith("eval_")]
        env = {(e[len("eval_"):],) : getattr(eval_, e) for e in env}
        for folder, _, files in os.walk(LIBRARY):
                for file in files:
                        with open(os.path.join(folder, file)) as f:
                                for e in exps.exps(f.read()):
                                        eval_.eval_(e, env)

        return env

env = make_env()
with open(sys.argv[1]) as f:
        for e in exps.exps(f.read()):
                eval_.eval_(e, env)
